# Generated by Django 3.0 on 2021-07-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_persona', models.CharField(max_length=100)),
                ('num_persona', models.CharField(max_length=100)),
            ],
        ),
    ]
